### ISSUE TITLE
Can't see hash or query 

### ISSUE THREAD

**Issue by illycz** [bnomei/kirby3-fingerprint#10]
I'm trying you great plugin, but I haven't hashes or queries on assets.

I call it within your function `<?= Bnomei\Fingerprint::css('assets/stylesheets/main.css') ?>`
I have disabled debug, and cache.

Plugin working, when I test https option, protocol is changed, but hashes or queries are missing.

Thanks for any suggestion

**Comment by bnomei** [comment]
i presume you are using most recent version?

 have you tried removing the cache folder the plugin creates? you can just delete it. 

the file „assets/stylesheets/main.css“ does exist right? the query can only be created for files that can be found and modification date checked.

**Comment by illycz** [comment]
Sorry I switchet to https://github.com/bvdputte/kirby-fingerprint which is good enought to me.

**Comment by bnomei** [comment]
to bad. so i do not know what went wrong. but it works with the other plugin and the same asset?

**Comment by illycz** [comment]
Yes, it works.
Next week I will try remove cached folder and send you feedback.

**Comment by illycz** [comment]
Still the same, also when I delete the bnomei/fingerprint folders...

Kirby 3.2.3
Your plugin installed throu composer, version 3.0.1

**Comment by bnomei** [comment]
i added some more unittests to check if hash gets created for css and js files. everything seems alright. i am out of ideas unless i can replicate the error. i would need the related

- config file part
- the css file location (not the file)
- the part of the template calling the helper
- the output of `F::modified($pathtoyoucssfile)`

i am not sure what happens if you have more than once cachebusting plugin installed. all others override the css/js helpers. my plugin is just calling them but it might mess up stuff. the other plugins might trim away the query string.

**Comment by illycz** [comment]
- config file part - I don't have anything related to this plugin
- the css file location - /assets/stylesheets/main.css
- the part of the template calling the helper - `<?= Bnomei\Fingerprint::css('assets/stylesheets/main.css') ?>`
- the output of `F::modified($pathtoyoucssfile)` - 1568019724

**Comment by bnomei** [comment]
`'bnomei.fingerprint.query' => false,` was the cuplrit. thanks. it should be fixed in `3.0.2`. 👋
